### ISSUE TITLE
Creating a new parameter group even with parameter_group_name 

### ISSUE THREAD

**Issue by diogonicoleti** [terraform-aws-modules/terraform-aws-rds#101]
I updated the module to version `1.24.0` and after this the plan shows me that a new parameter group will be create even specifying an existing parameter group (as described in here: https://github.com/terraform-aws-modules/terraform-aws-rds#conditional-creation).

The plan output:
```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create
  ~ update in-place

Terraform will perform the following actions:

  ~ module.db.module.db_instance.aws_db_instance.this
      parameter_group_name:      "common-postgres10" => "${var.parameter_group_name}"
      password:                  <sensitive> => <sensitive> (attribute changed)

  + module.db.module.db_parameter_group.aws_db_parameter_group.this
      id:                        <computed>
      arn:                       <computed>
      description:               "Database parameter group for db"
      name:                      <computed>
      name_prefix:               "db-"
      tags.%:                    "1"
      tags.Name:                 "db"


Plan: 1 to add, 1 to change, 0 to destroy.

------------------------------------------------------------------------

Note: You didn't specify an "-out" parameter to save this plan, so Terraform
can't guarantee that exactly these actions will be performed if
"terraform apply" is subsequently run.
```

and my module definition is:
```yaml
module "db" {
  source = "terraform-aws-modules/rds/aws"

  identifier = "db"

  engine            = "postgres"
  engine_version    = "10.6"
  instance_class    = "db.m4.large"
  multi_az          = true
  storage_type      = "gp2"
  allocated_storage = 200

  username = "postgres"
  password = "${var.password}"
  port     = "5432"

  vpc_security_group_ids = ["${data.aws_security_group.sg.id}"]
  parameter_group_name   = "common-postgres10"
  db_subnet_group_name   = "subnetdb"
  publicly_accessible    = false
  deletion_protection    = true

  backup_retention_period = "3"

  backup_window = "20:00-21:00"

  maintenance_window         = "Sun:21:00-Mon:03:00"
  auto_minor_version_upgrade = true

  monitoring_interval = "60"
  monitoring_role_arn = "${data.aws_iam_role.monitoring-role.arn}"
}
```

Is it correct?

FIY: In version `1.22.0` this works perfectly

**Comment by flmmartins** [comment]
+1. Also facing this issue

**Comment by jvelasquezjs** [comment]
Hey,

Faced the same, you just need to set this `create_db_parameter_group = false`. The module will no longer ignore the flag when the `parameter_group_name` is set.

**Comment by bobchaos** [comment]
I also bumped into this and a bit of code spelunking shows it's now impossible to pass a static parameter_group, as the value is passed down by the "main" module down to the "database" module like so:
```locals {
*snip*
parameter_group_name_id = "${module.db_parameter_group.this_db_parameter_group_id}"
*snip*
}
*snip*
parameter_group_name = "${local.parameter_group_name_id}"
*snip*``` then in `db_instance`...
`parameter_group_name = "${var.parameter_group_name}"`
which effectively makes it so we have to use the generated parameter group

**Comment by antonbabenko** [comment]
@bobchaos @jvelasquezjs What you are telling makes sense. Pull request, where this behavior is corrected, will be very much appreciated.

**Comment by jvelasquezjs** [comment]
@antonbabenko @bobchaos 

It works for me when doing this (v1.25)

```
module "db_parameter_group" {
  source = "vendor/modules/aws-db-parameter-group"
  name   = "my-rds-db-parameter-group"
  # [...]
}

module "stibo_dev_000001" {
  source              = "/vendor/modules/terraform-aws-rds"
  # [...]
  parameter_group_name        = "${module.db_parameter_group.default_id}"
  create_db_parameter_group = false
}
```

So it does not need any fixing...

**Comment by bobchaos** [comment]
That solution forces the user to understand the inner workings of the module. I can cook up a short PR, we just need the local to check for the var before module's output.

Similarly, I'd be tempted to remove the `create_db_parameter_group` var, it's redundant: either I name a param_group, or I create one, but I don't see why the module would create one then proceed immediately to ignoring it o.O

Any comments on that @antonbabenko before I open the PR?

**Comment by jvelasquezjs** [comment]
...If you are using the module, the very least is to read the input variables from the README, which IMO is pretty clear- I did not have to dig into the module to understand I had to change that to `false`. Anyhow, if it makes more sense to keep the previous behavior, then I am more than happy 😄

**Comment by bobchaos** [comment]
you can stop the param_group from spawning, but you still can't pass your own as an argument based on what's currently in master :O

**Comment by jvelasquezjs** [comment]
Are you pinned to `v1.25.0` or `master`?

**Comment by bobchaos** [comment]
latest from registry (prior to this anyhow, currently pinned to `1.22` so my own wrapping works)

**Comment by jvelasquezjs** [comment]
I am using `1.25` passing my own parameter_group `my_rds_param_group` and setting the `create_db_parameter_group` to `false` I do not see why you have to do a wrapping, it just works?

**Comment by jvelasquezjs** [comment]
I have updated my comment in case it was not clear that I am using my own module for creating a set of default parameter_groups and using this module to create the rds db instance that reference one of those parameter groups.

https://github.com/terraform-aws-modules/terraform-aws-rds/issues/101#issuecomment-473991364

**Comment by antonbabenko** [comment]
I agree with @jvelasquezjs , if you need to create a thing you have to set `create_db_parameter_group = true`.

@bobchaos There is no way to omit this variable and verify `parameter_group_name` due to a limitation of Terraform 0.11 which is related to "computed values can't be used in `count`".

Did I miss something and we should still fix something in this module? Or can we close this PR? (sorry for my lack of focus on this now)

**Comment by bobchaos** [comment]
` parameter_group_name = "${local.parameter_group_name_id}"` is the only value passed to the `db_instance` module, and that local looks like `parameter_group_name_id = "${module.db_parameter_group.this_db_parameter_group_id}"`, so it's impossible for you code snippet to work against current master as it would ignore your value and presumably error out on being unable to fetch the output of the module it's not spawning, which is going to need fixing before it gets reported as a bug in 1.26, regardless of how it looks in the registry version of `1.25`

**Comment by bobchaos** [comment]
noted about the the `create_db_parameter_group` var, I'll stick to fixing the `locals`

**Comment by jvelasquezjs** [comment]
@bobchaos, 

You are right, I was picking up an existing database, my bad. 

Thanks

**Comment by antonbabenko** [comment]
[v1.26.0](https://github.com/terraform-aws-modules/terraform-aws-rds/releases/v1.26.0) has been released.

Thanks @bobchaos and @jvelasquezjs for fast resolution.

**Comment by flmmartins** [comment]
Updating to 1.28.0 worked for me. Thanks!

**Comment by bryantbiggs** [comment]
@antonbabenko ok to close
